name: Deploy Lambda Function
on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install AWS CLI
        run: | 
          aws --version

          
